# Generated by Django 4.2.2 on 2023-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='abbreviation',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='nameshort',
            field=models.CharField(default='Atlantic', max_length=10),
            preserve_default=False,
        ),
    ]
