# Generated by Django 4.2.2 on 2023-06-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_division_abbreviation_division_nameshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nhl_id', models.IntegerField()),
                ('venue', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locationName', models.CharField(max_length=100)),
                ('teamName', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(max_length=1)),
                ('officialSiteUrl', models.URLField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division')),
            ],
            options={
                'ordering': ['division', 'name'],
            },
        ),
    ]
