# Generated by Django 4.2.2 on 2023-06-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=50),
        ),
    ]
