# Generated by Django 4.2.2 on 2023-06-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
    ]
