# Generated by Django 4.2.2 on 2023-06-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_player_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_stats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.player')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('birthCity', models.CharField(max_length=100)),
                ('birthStateProvince', models.CharField(max_length=100)),
                ('birthCountry', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('alternateCaptain', models.BooleanField()),
                ('captain', models.BooleanField()),
                ('rookie', models.BooleanField()),
                ('shootsCatches', models.CharField(max_length=2)),
                ('rosterStatus', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
    ]
