# Generated by Django 4.2.2 on 2023-06-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_player_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player_stats',
        ),
    ]
