# Generated by Django 4.2.2 on 2023-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_vitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_vitals',
            name='birthStateProvince',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
